[project]
name = "Roshan System - Python Version"
version = "19.200826"
dependences = [
    "pyside6",
    "pyside6_addons",
    "pyside6_essentials"
]

[tool.basedpyright]

typeCheckingMode = "standard"

reportUnusedImport = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportAny = false
reportExplicitAny = false
